In [1]:
import pandas as pd

# 1. read csv file from a url in pandas

### target website: https://www.football-data.co.uk/data.php

In [2]:
# reading 1 csv file from website
df_premier26=pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [3]:
#show dataframe
df_premier26

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,E0,19/04/2026,16:30,Man City,Arsenal,2,1,H,1,1,...,1.85,2.00,NaN,NaN,1.85,2.00,1.78,1.93,1.91,2.09
328,E0,20/04/2026,20:00,Crystal Palace,West Ham,0,0,D,0,0,...,1.90,1.95,NaN,NaN,1.90,2.05,1.82,1.93,NaN,NaN
329,E0,21/04/2026,20:00,Brighton,Chelsea,3,0,H,1,0,...,1.98,1.88,NaN,NaN,1.98,1.88,1.94,1.82,NaN,NaN
330,E0,22/04/2026,20:00,Bournemouth,Leeds,2,2,D,0,0,...,1.83,2.03,NaN,NaN,1.90,2.03,1.81,1.90,NaN,NaN
331,E0,22/04/2026,20:00,Burnley,Man City,0,1,A,0,1,...,1.93,1.93,NaN,NaN,1.93,1.93,1.88,1.87,NaN,NaN

In [4]:
# rename column
df_premier26.rename(columns={'FTHG':'home_goals',
                                'FTAG':'away_goals'},inplace=True)

In [5]:
# show database
df_premier26

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,E0,19/04/2026,16:30,Man City,Arsenal,2,1,H,1,1,...,1.85,2.00,NaN,NaN,1.85,2.00,1.78,1.93,1.91,2.09
328,E0,20/04/2026,20:00,Crystal Palace,West Ham,0,0,D,0,0,...,1.90,1.95,NaN,NaN,1.90,2.05,1.82,1.93,NaN,NaN
329,E0,21/04/2026,20:00,Brighton,Chelsea,3,0,H,1,0,...,1.98,1.88,NaN,NaN,1.98,1.88,1.94,1.82,NaN,NaN
330,E0,22/04/2026,20:00,Bournemouth,Leeds,2,2,D,0,0,...,1.83,2.03,NaN,NaN,1.90,2.03,1.81,1.90,NaN,NaN
331,E0,22/04/2026,20:00,Burnley,Man City,0,1,A,0,1,...,1.93,1.93,NaN,NaN,1.93,1.93,1.88,1.87,NaN,NaN

# 2. read  csv file from multiple urls with pandas

* https://www.football-data.co.uk/mmz4281/2526/E0.csv
* https://www.football-data.co.uk/mmz4281/2526/E1.csv
* https://www.football-data.co.uk/mmz4281/2526/E2.csv

In [6]:
#link structure
'https://www.football-data.co.uk/mmz4281/' + '2526/'+'E1.csv'

'https://www.football-data.co.uk/mmz4281/2526/E1.csv'

In [7]:
# root link
root="https://www.football-data.co.uk/mmz4281/"

## 2.1 multi leagues
* https://www.football-data.co.uk/mmz4281/2526/E0.csv
* https://www.football-data.co.uk/mmz4281/2526/E1.csv
* https://www.football-data.co.uk/mmz4281/2526/E2.csv
* https://www.football-data.co.uk/mmz4281/2526/E3.csv
* https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [8]:
#  creating list of leagues in 2026
leagues =['E0','E1','E2','E3','EC']
Frames=[]

In [9]:
# LOOP FOR READ MULTI LEAGUES and store in frame list
for league in leagues:
    df=pd.read_csv(root+'2526/'+league+'.csv',encoding='unicode_escape')
    Frames.append(df) ## stored in frames the df otherwise (eo can be replaced by e1 in df)

In [10]:
# length of frame
len(Frames) ## have 5 leagues csv data

5

In [11]:
Frames[4]

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,EC,18/04/2026,15:00,Truro,Carlisle,0,1,A,0,0,...,2.08,1.73,NaN,NaN,2.08,1.73,2.00,1.70,2.24,1.75
536,EC,18/04/2026,15:00,Wealdstone,Scunthorpe,1,1,D,0,0,...,1.90,1.90,NaN,NaN,1.90,1.90,1.83,1.85,1.93,2.02
537,EC,18/04/2026,17:30,Braintree Town,Rochdale,1,2,A,0,1,...,1.90,1.90,NaN,NaN,1.90,1.90,1.83,1.85,1.88,1.98
538,EC,18/04/2026,17:30,York,Yeovil,3,0,H,2,0,...,1.90,1.90,NaN,NaN,1.90,1.90,1.84,1.84,1.92,1.95
539,EC,21/04/2026,19:45,Hartlepool,Southend,4,3,H,1,1,...,1.85,1.95,NaN,NaN,1.90,1.95,1.85,1.83,NaN,NaN

# 2.2 for multiple seasons(2020,21,22...)

In [12]:
for season in range(20,26):
    print(str(season)+str(season+1))

2021
2122
2223
2324
2425
2526

In [13]:
#  creating list of leagues in 2026
leagues =['E0','E2','E3']
Frames=[]
# LOOP For range of seasons and insert new column
for league in leagues:
    for season in range (20,26):
        df=pd.read_csv(root + str(season)+str(season+1)+'/'+league+'.csv')
        df.insert(1,'season',season)
        Frames.append(df) ## stored in frames the df otherwise (eo can be replaced by e1 in df)

In [14]:
# total frames (6seasons * 3 leagues)
len(Frames)

18

In [15]:
# show 1st and last element (new season column was created)
Frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,Unnamed: 132
0,E3,25,02/08/2025,15:00,Accrington,Gillingham,1,1,D,0,...,1.88,1.76,2.12,1.98,1.88,1.92,1.83,2.09,1.88,NaN
1,E3,25,02/08/2025,15:00,Barnet,Fleetwood Town,0,2,A,0,...,1.85,2.29,1.65,2.08,1.85,2.00,1.74,2.04,1.93,NaN
2,E3,25,02/08/2025,15:00,Bristol Rvs,Harrogate,0,1,A,0,...,2.03,1.85,2.00,1.85,2.03,1.78,1.96,1.88,2.12,NaN
3,E3,25,02/08/2025,15:00,Cambridge,Cheltenham,1,0,H,0,...,1.88,1.88,1.97,1.98,1.88,1.90,1.83,1.98,2.00,NaN
4,E3,25,02/08/2025,15:00,Chesterfield,Barrow,1,0,H,1,...,2.03,1.79,2.06,1.80,2.07,1.73,2.02,1.87,2.13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,E3,25,18/04/2026,15:00,Oldham,Salford,1,2,A,0,...,1.88,NaN,NaN,1.98,1.88,1.90,1.82,2.04,1.94,NaN
525,E3,25,18/04/2026,15:00,Tranmere,Bristol Rvs,1,2,A,0,...,1.73,NaN,NaN,2.15,1.73,2.06,1.69,2.14,1.85,NaN
526,E3,25,21/04/2026,19:45,Cambridge,Grimsby,1,2,A,1,...,1.98,NaN,NaN,2.23,1.98,1.94,1.79,NaN,NaN,NaN
527,E3,25,21/04/2026,19:45,Cheltenham,Tranmere,1,3,A,1,...,1.88,NaN,NaN,1.98,2.00,1.85,1.87,NaN,NaN,NaN
528,E3,25,23/04/2026,20:00,Salford,Bromley,2,0,H,0,...,1.88,NaN,NaN,1.98,1.88,1.89,1.83,NaN,NaN,NaN

# 3. organize all in dictionary

In [16]:
# creating dictonary with name of league as a key
dict_countries={'spanish la liga':'SP1','spanish segunda division'
                :'SP2','german bundesliga1 ':'D1','german bundesliga2 ':'D2',
                'english premier league':'E0','english league 1':'E2','english league 2':'E3'
}

In [17]:
# get a dictionary element
dict_countries['spanish la liga']

'SP1'

In [18]:
for league in dict_countries:
    print (dict_countries[league])

SP1
SP2
D1
D2
E0
E2
E3

In [19]:
dict_historical_data={}
#leagues =['E0','E2','E3']

# LOOP For range of seasons and insert new column
for league in dict_countries:
    Frames=[]
    for season in range (20,26):
        df=pd.read_csv(root + str(season)+str(season+1)+'/'+dict_countries[league]+'.csv')
        df.insert(1,'season',season)
        Frames.append(df) 
    df_concat = pd.concat(Frames)
    dict_historical_data[league]=df_concat

In [20]:
# dataframe inside dic_historical_data
dict_historical_data.keys()

dict_keys(['spanish la liga', 'spanish segunda division', 'german bundesliga1 ', 'german bundesliga2 ', 'english premier league', 'english league 1', 'english league 2'])

In [21]:
dict_historical_data['english league 1']

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E2,20,12/09/2020,15:00,Accrington,Peterboro,2,0,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E2,20,12/09/2020,15:00,Crewe,Charlton,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E2,20,12/09/2020,15:00,Doncaster,Milton Keynes Dons,1,1,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E2,20,12/09/2020,15:00,Fleetwood Town,Burton,2,1,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E2,20,12/09/2020,15:00,Gillingham,Hull,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,E2,25,21/04/2026,19:45,Doncaster,Lincoln,0,2,A,0,...,2.08,2.90,3.50,2.30,3.00,3.4,2.30,3.00,3.3,2.30
521,E2,25,21/04/2026,19:45,Rotherham,Luton,0,2,A,0,...,1.50,6.00,4.33,1.50,6.00,4.6,1.48,6.00,4.6,1.48
522,E2,25,21/04/2026,19:45,Stevenage,Barnsley,1,0,H,1,...,4.80,1.67,3.60,5.25,1.73,3.6,4.80,1.73,3.6,4.80
523,E2,25,21/04/2026,19:45,Stockport,Mansfield,0,1,A,0,...,5.10,1.50,4.50,5.75,1.53,4.5,5.50,1.53,4.5,5.25
524,E2,25,22/04/2026,19:45,Cardiff,Port Vale,1,0,H,0,...,8.00,1.36,5.00,7.50,1.40,4.8,7.50,1.40,4.6,7.00